function AddTextEntry(key, value)
Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
AddTextEntry('AUDI', 'Audi')
AddTextEntry('COSSIE', 'Escort RS Cosworth')
AddTextEntry('FORD', 'Ford')
AddTextEntry('GSX', 'Eclipse GS-T')
AddTextEntry('MITSUBISHI', 'Mitsubishi')
AddTextEntry('MKVR32', 'Golf R32')
AddTextEntry('RS4', 'RS4')
AddTextEntry('VOLKSWAGEN', 'Volkswagen')
AddTextEntry('STEW_WHEEL_01', 'Audi RS4 Wheels')
AddTextEntry('STEW_WHEEL_02', 'Mitsubishi GS-T Wheels')
AddTextEntry('STEW_WHEEL_03', 'Ford Escort RS Cosworth Wheels')
AddTextEntry('STEW_WHEEL_04', 'VW Golf R32 Wheels')
AddTextEntry('STEW_WHEEL_05', 'Volk TE37V (Deep Dish)')
AddTextEntry('STEW_WHEEL_06', 'Generic Steelie')
AddTextEntry('STEW_WHEEL_07', 'Fifteen 52 Tarmacs')
AddTextEntry('STEW_WHEEL_08', 'Stews Special MK1')
AddTextEntry('STEW_WHEEL_09', 'Stews Special MK2')
AddTextEntry('STEW_WHEEL_10', 'Rotiform TMB')
end)